Projekat/Models/Racun.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Projekat.Models
{
    [Table("Racuni")]
    public class Racun : EntityBase
    {
        [DisplayName("Broj fakture")]
        public int BrojFakture { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Datum dospjeća fakture")]
        public DateTime? DatumDospjecaFakture { get; set; }

        [DisplayName("Primatelj računa")]
        public string PrimateljRacuna { get; set; }
        
        [Required]
        public float PDV { get; set; }

        public string StvarateljRacunaId { get; set; }
        [DisplayName("Stvaratelj računa")]
        public ApplicationUser StvarateljRacuna { get; set; }

        public bool IsDeleted { get; set; }

        public ICollection<RacunStavka> RacunStavke { get; set; }
    }
}

Projekat/Controllers/RacunController.cs
using Projekat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using Projekat.Models.DTOs;
using System.Threading;
using System.Text.RegularExpressions;
using System.ComponentModel.Composition;
using Projekat.VATContainer;
using Microsoft.Ajax.Utilities;
using Projekat.Container;

namespace Projekat.Controllers
{
    [Authorize]
    public class RacunController : Controller
    {
        ApplicationDbContext Context = new ApplicationDbContext();

        [ImportMany]
        public IEnumerable<Lazy<IVATRate, IVATRateMetaData>> MEFVATList { get; private set; }

        // GET: Racun
        public ActionResult Index()
        {
            List<Racun> Racuni = Context.Racuni.Where(x => x.IsDeleted == false).Include(x => x.StvarateljRacuna).ToList();
            return View(Racuni);
        }

        // GET: Racun/Details/5
        public ActionResult Details(int id)
        {
            var Racun = Context.Racuni.Where(x => x.IsDeleted == false).Include(x => x.StvarateljRacuna).FirstOrDefault(x => x.Id == id);
            if (Racun == null)
                return RedirectToAction("Index");

            var RacunStavke = Context.RacuniStavke.Where(x => x.RacunId == id && x.IsDeleted == false).ToList();

            RacunStavkaDto result = new RacunStavkaDto()
            {
                Id = id,
                Racun = Racun,
                Stavke = RacunStavke,
                UkupnaCijenaBezPDVa = RacunStavke.Sum(x => x.CijenaBezPDV * x.Kolicina),
                UkupnaCijenaSaPDVom = RacunStavke.Sum(x => x.CijenaSaPDV * x.Kolicina)
            };

            return View(result);

        }

        // GET: Racun/Create

        public ActionResult Create()
        {
            Racun racun = new Racun
            {
                CreateDate = DateTime.Today,
                BrojFakture = GetIduciBrojFakture(),
                DatumDospjecaFakture = null
            };

            ViewBag.VATList = MEFVATList
                .Select(x => x.Value)
                .DistinctBy(x => x.GetCountryName())
                .Select(x => new SelectListItem
            {
                Text = x.GetCountryName() + " (" + x.GetVATRate() + "%)",
                Value = ((float)x.GetVATRate() / 100).ToString()
            }).Distinct().ToList();

            return View(racun);
        }

        // POST: Racun/Create
        [HttpPost]
        public ActionResult Create(Racun racun)
        {

            try
            {
                // TODO: Add insert logic here
                racun.BrojFakture = GetIduciBrojFakture();
                racun.CreateDate = DateTime.Now;
                racun.UpdateDate = DateTime.Now;
                racun.StvarateljRacunaId = User.Identity.GetUserId();
                Context.Racuni.Add(racun);
                Context.SaveChanges();
                return RedirectToAction("Edit", new { @Id = racun.Id });
            }
            catch (Exception e)
            {
                return View();
            }
        }

        private int GetIduciBrojFakture()
        {
            int IduciBrojFakture = 1;

            int ZadnjiBrojFakture = Context.Racuni.Select(x => x.BrojFakture).DefaultIfEmpty(0).Max();
            if (ZadnjiBrojFakture != 0)
                IduciBrojFakture = ZadnjiBrojFakture + 1;
            return IduciBrojFakture;
        }

        // GET: Racun/Edit/5
        public ActionResult Edit(int id)
        {
            var Racun = Context.Racuni
                .Where(x => x.IsDeleted == false)
                .Where(x => x.Id == id)
                .Include(x => x.StvarateljRacuna)
                .FirstOrDefault();
            if (Racun == null)
            {
                return RedirectToAction("Index");
            }

            Racun.RacunStavke = Context.RacuniStavke.Where(x => x.RacunId == id && x.IsDeleted == false).ToList();

            string DecimalSeparator = Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator;

            ViewBag.PricePattern = "^[0-9]+(" + Regex.Escape(DecimalSeparator) + "[0-9]{2})?$";
            return View(Racun);
        }

        // GET: Racun/Delete/5
        public ActionResult Delete(int id)
        {
            var Racun = Context.Racuni.Find(id);
            if (Racun != null)
            {
                Racun.IsDeleted = true;
                Context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        // POST: Racun/DodajStavku
        [HttpPost]
        public ActionResult DodajStavku(RacunStavka racunStavka)
        {
            var Racun = Context.Racuni.Find(racunStavka.RacunId);
            if (Racun == null)
                return RedirectToAction("Index");

            if (racunStavka.Id != 0)
            {
                var ExistingStavka = Context.RacuniStavke.Where(x => x.IsDeleted == false).FirstOrDefault(x => x.Id == racunStavka.Id);
                ExistingStavka.Opis = racunStavka.Opis;
                ExistingStavka.Kolicina = racunStavka.Kolicina;
                ExistingStavka.CijenaBezPDV = racunStavka.CijenaBezPDV;

                ExistingStavka.UpdateDate = DateTime.Now;
            }
            else
            {
                racunStavka.CreateDate = DateTime.Now;
                racunStavka.UpdateDate = DateTime.Now;
                Context.RacuniStavke.Add(racunStavka);
            }
            Context.SaveChanges();

            return RedirectToAction("Edit", new { Id = racunStavka.RacunId });
        }

        // GET: Racun/UkloniStavku/5
        public ActionResult UkloniStavku(int id)
        {
            var RacunStavka = Context.RacuniStavke.Find(id);
            if (RacunStavka != null)
            {
                RacunStavka.IsDeleted = true;
                Context.SaveChanges();

                return RedirectToAction("Edit", new { Id = RacunStavka.RacunId });
            }
            return RedirectToAction("Index");
        }
    }
}

Projekat/Views/Racun/Create.cshtml
@model Projekat.Models.Racun
@using Projekat.Helper

@{
    ViewBag.Title = "Create";
    List<SelectListItem> VATList = ViewBag.VATList;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Racun</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BrojFakture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojFakture, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                @Html.ValidationMessageFor(model => model.BrojFakture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumDospjecaFakture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumDospjecaFakture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumDospjecaFakture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrimateljRacuna, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrimateljRacuna, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrimateljRacuna, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PDV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.PDV, VATList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PDV, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Projekat/Views/Racun/Details.cshtml
@model Projekat.Models.DTOs.RacunStavkaDto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>


<div class="form-horizontal">
    <h4>Racun</h4>
    <hr />
    <div class="form-group">
        @Html.LabelFor(model => model.Racun.BrojFakture, htmlAttributes: new { @class = "control-label col-md-2 no-padding" })
        <div class="col-md-10">
            @Model.Racun.BrojFakture
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Racun.CreateDate, htmlAttributes: new { @class = "control-label col-md-2 no-padding" })
        <div class="col-md-10">
            @Model.Racun.CreateDate.Value.ToShortDateString()
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Racun.DatumDospjecaFakture, htmlAttributes: new { @class = "control-label col-md-2 no-padding" })
        <div class="col-md-10">
            @Model.Racun.DatumDospjecaFakture.Value.ToShortDateString()
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Racun.PrimateljRacuna, htmlAttributes: new { @class = "control-label col-md-2 no-padding" })
        <div class="col-md-10">
            @Model.Racun.PrimateljRacuna
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Racun.StvarateljRacuna, htmlAttributes: new { @class = "control-label col-md-2 no-padding" })
        <div class="col-md-10">
            @Model.Racun.StvarateljRacuna.Email
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Racun.PDV, htmlAttributes: new { @class = "control-label col-md-2 no-padding" })
        <div class="col-md-10">
            @(Model.Racun.PDV * 100)%
        </div>
    </div>

    <br />
</div>

<div>
    <h4>Stavke računa</h4>
    <table class="table">
        <thead>

            <tr>
                <th>
                    Opis
                </th>
                <th>
                    Kolicina
                </th>
                <th>
                    Cijena bez PDV
                </th>
                <th>
                    Ukupna cijena bez PDV
                </th>
                <th>
                    Ukupna cijena sa PDV
                </th>
            </tr>
        </thead>
        <tbody>


            @foreach (var item in Model.Stavke)
            {
                <tr>
                    <td>
                        @Html.DisplayTextFor(model => item.Opis)
                    </td>
                    <td>
                        @Html.DisplayTextFor(model => item.Kolicina)
                    </td>
                    <td>
                        @item.CijenaBezPDV.ToString("C")
                    </td>
                    <td>
                        @((item.CijenaBezPDV * item.Kolicina).ToString("C"))
                    </td>
                    <td>
                        @((item.CijenaSaPDV * item.Kolicina).ToString("C"))
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td>
                </td>
                <td>
                </td>
                <td>
                </td>
                <td><strong>@Model.UkupnaCijenaBezPDVa.ToString("C")</strong></td>

                <td><strong>@Model.UkupnaCijenaSaPDVom.ToString("C")</strong></td>
            </tr>
        </tfoot>

    </table>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Projekat/Views/Racun/Edit.cshtml
@model Projekat.Models.Racun
@using Projekat.Helper

@{
    ViewBag.Title = "Edit";
    object PricePattern = ViewBag.PricePattern;
}

<h2>@ViewBag.Title</h2>

<div class="form-horizontal">
    <h4>Racun</h4>
    <hr />
    <div class="form-group">
        @Html.LabelFor(model => model.BrojFakture, htmlAttributes: new { @class = "control-label col-md-2 no-padding" })
        <div class="col-md-10">
            @Model.BrojFakture
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2 no-padding" })
        <div class="col-md-10">
            @Model.CreateDate.Value.ToShortDateString()
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DatumDospjecaFakture, htmlAttributes: new { @class = "control-label col-md-2 no-padding" })
        <div class="col-md-10">
            @Model.DatumDospjecaFakture.Value.ToShortDateString()
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PrimateljRacuna, htmlAttributes: new { @class = "control-label col-md-2 no-padding" })
        <div class="col-md-10">
            @Model.PrimateljRacuna
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StvarateljRacuna, htmlAttributes: new { @class = "control-label col-md-2 no-padding" })
        <div class="col-md-10">
            @Model.StvarateljRacuna.Email
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PDV, htmlAttributes: new { @class = "control-label col-md-2 no-padding" })
        <div class="col-md-10">
            @(Model.PDV * 100)%
        </div>
    </div>
</div>

<br />

@using (Html.BeginForm("DodajStavku", "Racun"))
{
    @Html.AntiForgeryToken()
    <input type="hidden" name="RacunId" value="@Model.Id" />
    <div>
        <h4>Stavke računa</h4>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Opis
                    </th>
                    <th>
                        Kolicina
                    </th>
                    <th>
                        Cijena bez PDV
                    </th>
                    <th>
                        Ukupna cijena bez PDV-a
                    </th>
                    <th>
                        Ukupna cijena sa PDV-om
                    </th>
                    <th>Akcija</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model.RacunStavke)
                {
                    <tr class="stavka-row" data-stavka-id="@item.Id">
                        <td class="opis" data-value="@item.Opis">
                            @Html.DisplayTextFor(model => item.Opis)
                        </td>
                        <td class="kolicina" data-value="@item.Kolicina">
                            @Html.DisplayTextFor(model => item.Kolicina)
                        </td>
                        <td class="cijenabezpdv" data-value="@item.CijenaBezPDV">
                            @item.CijenaBezPDV.ToString("C")
                        </td>
                        <td>
                            @((item.CijenaBezPDV * item.Kolicina).ToString("C"))
                        </td>
                        <td>
                            @((item.CijenaSaPDV * item.Kolicina).ToString("C"))
                        </td>
                        <td>
                            <button type="button" class="btn btn-primary izmijeni-stavku">Izmijeni</button>
                            @Html.ActionLink("Ukloni", "UkloniStavku", new { @Id = item.Id }, new { @class = "btn btn-danger" } )
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td>
                        @Html.TextBox("Opis", null, new { @class = "form-control", @placeholder = "Opis", @required = true })
                    </td>
                    <td>
                        @Html.TextBox("Kolicina", null, new { @class = "form-control", type = "number", min = 1, max = 1000, step = 1, @placeholder = "Kolicina", @required = true })
                    </td>
                    <td>
                        @Html.TextBox("CijenaBezPDV", null, new { @class = "form-control", type = "text", @placeholder = "Cijena bez PDV-a", pattern = PricePattern, @required = true })
                    </td>
                    <td>
                        <input type="hidden" name="Id" id="Id" value="0" />
                        <button type="submit" class="btn btn-primary" id="StavkaButton">Dodaj</button>
                        <button type="button" class="btn btn-danger hidden" id="OtkaziButton">Otkaži</button>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                </tr>
            </tfoot>

        </table>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts{
    <script src="~/Scripts/edit-stavka.js"></script>
}

Projekat/Views/Racun/Index.cshtml
@model IEnumerable<Projekat.Models.Racun>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BrojFakture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatumDospjecaFakture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PDV)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrimateljRacuna)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StvarateljRacuna)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.BrojFakture)
    </td>
    <td>
        @item.DatumDospjecaFakture.Value.ToShortDateString()
    </td>
    <td>
        @(item.PDV * 100)%
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PrimateljRacuna)
    </td>
    <td>
        @item.CreateDate.Value.ToShortDateString()
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.StvarateljRacuna.Email)
    </td>

    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
    </td>
</tr>
}

</table>